<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eCommerce.SharedLibrary\eCommerce.SharedLibrary.csproj" />
    <ProjectReference Include="..\ProductApi.Application\ProductApi.Application.csproj" />
    <ProjectReference Include="..\ProductApi.Domain\ProductApi.Domain.csproj" />
  </ItemGroup>

</Project>
