# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo
# version: "3.8"

###
#History:
#  2 docker ps
#  3 docker stop mongo
#  7 docker ps
# 10 docker-compose up -d
# 12 docker-compose down
# 13 docker-compose up -d
###

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    # restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    # restart: unless-stopped

volumes:
  mongodbdata:
  rabbitmqdata:

### in  C:\Projects\BikeStores\BikeStores\JulioCasal\Microservices\Play.Common>
# dotnet pack -p:PackageVersion=1.0.2 -o C:\Projects\BikeStores\packages

### in C:\Projects\BikeStores\BikeStores\JulioCasal\Microservices\Play.Catalog\JC.Play.Catalog.Contracts
# dotnet pack -o C:\Projects\BikeStores\packages
