<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eCommerce.SharedLibrary\eCommerce.SharedLibrary.csproj" />
    <ProjectReference Include="..\ProductApi.Application\ProductApi.Application.csproj" />
    <ProjectReference Include="..\ProductApi.Infrastructure\ProductApi.Infrastructure.csproj" />
  </ItemGroup>

</Project>
